Links to videos on Channel9
zpbappi/rx-workshop-challenges pull request #1
Opened 2020-09-17 12:34 UTC by cb504

Started numbered list at zero to align videos with challenges.

2020-09-23 02:57 UTC, zpbappi requested changes

2020-09-23 02:57 UTC, zpbappi commented on README.md
> +[unsolved](https://github.com/cb504/rx-workshop-challenges/tree/unsolved) branch of this repository.
Will you please keep the url unchanged?

2020-09-23 02:57 UTC, zpbappi commented on README.md
> +- [x] Challenge 7 - Programming the Cloud
What changed here?

2020-09-27 09:01 UTC, cb504 commented
I will close this PR, and redo it from a branch. I will try and get this done later this week.

2020-09-27 09:01 UTC, closed without merging